{% set name = "dagster_cron" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 7c754dcd6773b2152b3b312ce1272887bd095a6e31ead2cadd331e0f36bdd167

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - python-crontab >=2.3.8

test:
  imports:
    - dagster_cron

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-cron
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A Dagster integration for cron

extra:
  recipe-maintainers:
    - conda-forge/dagster
