{% set name = "dagster_cron" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 66d08af2a2eec8c1c738021230ce1fc3356abf47ce510c954cad8db4495054de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - python-crontab >=2.3.8

test:
  imports:
    - dagster_cron

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-cron
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A Dagster integration for cron

extra:
  recipe-maintainers:
    - conda-forge/dagster
